version: '3.8'

services:
  pgdb:
    container_name: zenith_dev_db
    image: postgres:14.3
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: zenith_dev_dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zenith.com
      PGADMIN_DEFAULT_PASSWORD: zenith
    ports:
      - '5050:80'
    depends_on:
      - pgdb

volumes:
  pgdata:
  pgadmin:
