services:
  pgdb:
    image: postgres:17
    container_name: zenith_dev_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MESSENGER_PASSWORD: ${MESSENGER_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - database
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: zenith_dev_dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    networks:
      - database
    depends_on:
      - pgdb
    volumes:
      - dbadmin:/var/lib/pgadmin

  app:
    container_name: zenith_dev_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - database
    volumes:
      - app:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    depends_on:
      - pgdb

networks:
  database:
    driver: bridge

volumes:
  pgdata:
  node_modules:
  app:
  dbadmin:
