version: '3.8'

services:
  pgdb:
    image: postgres:17
    container_name: zenith_dev_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MESSENGER_PASSWORD: ${MESSENGER_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - database
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: zenith_dev_dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    networks:
      - database
    depends_on:
      - pgdb
    volumes:
      - dbadmin:/var/lib/pgadmin

networks:
  database:
    driver: bridge

volumes:
  pgdata:
  dbadmin:
