services:
  pgdb:
    container_name: zenith_dev_db
    image: postgres:14.3
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: zenith_dev_dbadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - pgdb
    volumes:
      - pgadmin:/var/lib/pgadmin/data

  app:
    container_name: zenith_dev_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - app:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    depends_on:
      - pgdb

volumes:
  app:
  node_modules:
  db:
  pgadmin:
